version: '3.9'
services:
  api-1:
    build:
      dockerfile: ./Dockerfile
      target: development
      context: .
    command: npm run serve
    expose:
      - 3333
    ports:
      - "4010:3333"
      - "9010:9669"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5010
      DATABASE_USER: api1
      DATABASE_NAME: api1
      DATABASE_PASSWORD: TopSecret123
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    name: example_dev_network
    driver: bridge
